### ISSUE TITLE
GitHub services going away Jan 31 2019 breaks the design

### ISSUE THREAD

**Issue by gene1wood** [gene1wood/birch-girder#21]
Birch Girder depends on the [`amazonsns`](https://github.com/github/github-services/blob/master/docs/amazonsns) GitHub service to enable comments in GitHub issues to trigger sending emails to users. [GitHub Services will stop working on Jan 31 2019](https://developer.github.com/changes/2018-10-01-denying-new-github-services/). As a result at that point @ mentions in GitHub issues will stop triggering sending of emails to users.

We need to come up with a new webhook endpoint to use
* We could obviously use API Gateway and Lambda, but this will cost $3.50/month and breaks the free design principle
* We could try using hook.io which gives 1000 invocations per month free. Downside is a hard limit at 1000 emails sent per month (above which it's $10 a month). And the docs are full of broken links and there have been no commits in the last 8 months. This would involve writing a hook.io service which
  * Accepted the GitHub webhook
  * Validated the webhook payload by [calculating a hash](https://developer.github.com/webhooks/securing/) from a secret stored as [an environment variable](https://hook.io/docs#env)
  * Made an AWS API call to SNS to send the payload using credentials also pulled from environment variables

**Comment by SuperQ** [comment]
The API gateway is free for the first 12 months, is that "free enough"? Users who really want free can rotate their signup every 12 months.

**Comment by gene1wood** [comment]
I'm reluctant to go that route. Rotating signup which would require new credit cards and billing addresses seems extreme. For IO Coop, since we have but one debit card, I don't think that would work well for us.

I think at the moment because it probably won't take much work, I'll try the hook.io route despite it appearing somewhat abandoned. I emailed the author to ask what's up but haven't heard back. I'm hoping that maybe it's on autopilot because it has paid subscriptions and so maybe it's making enough revenue to pay for the infrastructure but the author has moved onto other things. Not ideal but maybe acceptable as a low effort interim so things don't break on Jan 31.

**Comment by gene1wood** [comment]
We can't use Zapier because Amazon SNS is a premium app.

**Comment by gene1wood** [comment]
Got it working with hook.io. I'll submit a PR with new deploy code and instructions for using it.

**Comment by gene1wood** [comment]
I completed the hook.io integration in #24 but opted not to merge it.

Now with GitHub Actions I've implemented #25 which uses GitHub Actions and have merged it resolving this issue.
